### PR TITLE
Add CI integration for Netlify

### PR DESCRIPTION
**Pull request by imorente**
I'd like to submit a PR to  [dangerjs](https://github.com/danger/danger-js) to add Netlify as a CI provider.

I pretty much took one of the existing providers, [BuddyBuild](https://github.com/netlify/danger-js/blob/master/source/ci_source/providers/BuddyBuild.ts), and changed the names of the ENV variables

Would love some extra 👀 and comments from someone else in the team before sending it.

### CODE REVIEW

**Comment by imorente** [comment]
@kitop @sw-yx – what do you think?

**Comment by biilmann** [comment]
LGTM

**Comment by imorente** [comment]
@bcomnes – I saw the build bot sets a non-documented environment variable `NETLIFY_BUILD_BASE`. I'm using that to identify Netlify as the CI because it's the only env variable I found that had the name "NETLIFY" in it. How can I make sure that we don't change that variable name? 😅 Add a comment in the build bot code perhaps?

**Comment by imorente** [comment]
thanks @biilmann  – opened another PR against danger:master

**Comment by swyxio** [comment]
wow, very cool! unfortunately i have never used danger before but it'd be great to be a provider. let me know when its done and i'd be happy to write it up!

**Comment by kitop** [comment]
👍 🎉

**Comment by bcomnes** [comment]
> @bcomnes – I saw the build bot sets a non-documented environment variable NETLIFY_BUILD_BASE. I'm using that to identify Netlify as the CI because it's the only env variable I found that had the name "NETLIFY" in it. How can I make sure that we don't change that variable name? 😅 Add a comment in the build bot code perhaps?

Not sure, I guess we'll just promise not to change it?!? 😅

**Comment by bcomnes** [comment]
We really should come up with a master list definition in the build-bot or wherever it makes sense of all variables, noting public/private status.  If it's there, people will use it.

**Pull request closed without merging**
